export const metadata = { title: "Terms of Service — QR Kit" };
export default function Page() {
  return (
    <main className="container py-8 max-w-4xl">
      <h1 className="text-3xl font-bold mb-6">Terms of Service</h1>
      
      <div className="prose prose-lg dark:prose-invert max-w-none space-y-6">
        <p className="text-lg text-muted-foreground">
          Last updated: October 2025
        </p>

        <section>
          <h2 className="text-2xl font-semibold mt-8 mb-4">Acceptance of Terms</h2>
          <p>
            By accessing and using QR Kit ("the Service"), you accept and agree to be bound by these 
            Terms of Service. If you do not agree to these terms, please do not use the Service. We 
            reserve the right to modify these terms at any time, and your continued use of the Service 
            constitutes acceptance of any changes.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mt-8 mb-4">Description of Service</h2>
          <p>
            QR Kit is a free, browser-based QR code generator that allows users to create QR codes for 
            URLs, Wi-Fi credentials, and vCard contact information. All QR code generation happens 
            client-side in your browser, and we do not store, collect, or have access to the data you 
            encode in your QR codes.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mt-8 mb-4">Use of Service</h2>
          <p>
            <strong>Permitted Use:</strong> You may use QR Kit for any lawful purpose to generate QR codes 
            for personal, commercial, or non-commercial use. You retain all ownership rights to any QR codes 
            you generate using the Service.
          </p>
          <p>
            <strong>Prohibited Use:</strong> You may not use the Service to:
          </p>
          <ul className="list-disc pl-6 space-y-2">
            <li>Generate QR codes that link to illegal content, malware, phishing sites, or other harmful materials</li>
            <li>Violate any applicable laws or regulations</li>
            <li>Infringe upon intellectual property rights of others</li>
            <li>Attempt to reverse engineer, decompile, or otherwise extract the source code of the Service</li>
            <li>Use automated systems or scripts to generate excessive numbers of QR codes in a manner that impacts service availability</li>
          </ul>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mt-8 mb-4">Disclaimer of Warranties</h2>
          <p>
            QR Kit is provided "as is" and "as available" without any warranties of any kind, either 
            express or implied, including but not limited to warranties of merchantability, fitness for 
            a particular purpose, non-infringement, or course of performance.
          </p>
          <p>
            We do not warrant that:
          </p>
          <ul className="list-disc pl-6 space-y-2">
            <li>The Service will be uninterrupted, secure, or error-free</li>
            <li>The results obtained from using the Service will be accurate or reliable</li>
            <li>QR codes generated will be compatible with all QR code readers</li>
            <li>Any errors in the Service will be corrected</li>
          </ul>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mt-8 mb-4">Limitation of Liability</h2>
          <p>
            To the maximum extent permitted by law, QR Kit, its operators, affiliates, and service 
            providers shall not be liable for any indirect, incidental, special, consequential, or 
            punitive damages, or any loss of profits or revenues, whether incurred directly or indirectly, 
            or any loss of data, use, goodwill, or other intangible losses resulting from:
          </p>
          <ul className="list-disc pl-6 space-y-2">
            <li>Your use or inability to use the Service</li>
            <li>Any unauthorized access to or use of our servers</li>
            <li>Any bugs, viruses, or other harmful code that may be transmitted to or through the Service</li>
            <li>Any errors or omissions in QR codes generated by the Service</li>
            <li>The content, actions, or inactions of third parties who scan or use QR codes you generate</li>
          </ul>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mt-8 mb-4">Indemnification</h2>
          <p>
            You agree to indemnify, defend, and hold harmless QR Kit and its operators from any claims, 
            damages, losses, liabilities, and expenses (including reasonable attorney's fees) arising from 
            your use of the Service, your violation of these Terms, or your violation of any rights of 
            another party.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mt-8 mb-4">Third-Party Content and Services</h2>
          <p>
            The Service may display advertisements and links to third-party websites. We are not responsible 
            for the content, privacy policies, or practices of any third-party websites or services. Your 
            interactions with third-party advertisements and websites are solely between you and the third party.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mt-8 mb-4">Termination</h2>
          <p>
            We reserve the right to terminate or suspend your access to the Service at any time, without 
            notice, for any reason, including violation of these Terms. Upon termination, your right to 
            use the Service will immediately cease.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mt-8 mb-4">Governing Law</h2>
          <p>
            These Terms shall be governed by and construed in accordance with applicable laws, without 
            regard to conflict of law provisions. Any disputes arising from these Terms or your use of 
            the Service shall be resolved in the appropriate courts.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mt-8 mb-4">Contact Information</h2>
          <p>
            If you have any questions about these Terms of Service, please contact us at{' '}
            <a href="mailto:support@platovalabs.com" className="text-primary hover:underline">
              support@platovalabs.com
            </a>.
          </p>
        </section>
      </div>
    </main>
  );
}